# Use postgres/example user/password credentials
version: '3.1'

services:

  web:
    build: .
    ports:
    - 8080:80

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
    - db:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
    - 8880:8080

  redis:
    image: redis

volumes:
  db: {}